spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/e_commerce?useSSL=false
    password: Saurabh@123
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: springbootpractice94@gmail.com
    password: eltrprwwqivdblap
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084

